// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type DocumentInformation struct {
	Hash       string
	Progress   string
	Percentage float64
	Device     string
	DeviceID   string
	Timestamp  time.Time
	Username   string
}

type UserAccount struct {
	Username     string
	PasswordHash string
}
