// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Document struct {
	Hash       string
	Progress   string
	Percentage float64
	Device     string
	Deviceid   string
	Timestamp  time.Time
	Userid     int64
}

type User struct {
	ID           int64
	Username     string
	Passwordhash string
	Isactive     bool
	Isadmin      bool
}
